apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
      - userARN: arn:aws:iam::789980025226:user/github-ci
        username: github-ci
        groups:
          - system:masters