apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
#      - userarn: arn:aws:iam::789980025226:user/github-ci
#        username: github-ci
#        groups:
#          - system:masters
  mapUsers: |
      - rolearn: arn:aws:iam::789980025226:role/sm-actions-role
        username: sm-actions-role
        groups:
          - system:masters